### ISSUE TITLE
MissingTokenError: (missing_token) Missing access token parameter.

### ISSUE THREAD

**Issue by rjollos** [trac-hacks/trac-github#97]
I've been noticing tracebacks like this in the logs, at least twice in the past week. I'm unsure of how to reproduce the issue, but maybe we can trap and display a nicer error to the user. Most likely, the error results in the standard Trac error page with a traceback.

```
2016-02-15 01:33:21,870 Trac[main] ERROR: Internal Server Error: <RequestWithSession "GET '/github/oauth?code=1042415f1e75a2ef5c07&state=o5EZcGeiCqVJ5zZqShpAuWIchPdUmn'">, referrer 'https://bugs.jqueryui.com/ticket/10458'
Traceback (most recent call last):
  File "/var/www/bugs.jqueryui.com/private/pve/local/lib/python2.7/site-packages/trac/web/main.py", line 554, in _dispatch_request
    dispatcher.dispatch(req)
  File "/var/www/bugs.jqueryui.com/private/pve/local/lib/python2.7/site-packages/trac/web/main.py", line 247, in dispatch
    resp = chosen_handler.process_request(req)
  File "/var/www/bugs.jqueryui.com/private/pve/local/lib/python2.7/site-packages/tracext/github.py", line 56, in process_request
    self._do_oauth(req)
  File "/var/www/bugs.jqueryui.com/private/pve/local/lib/python2.7/site-packages/tracext/github.py", line 77, in _do_oauth
    client_secret=client_secret)
  File "/var/www/bugs.jqueryui.com/private/pve/local/lib/python2.7/site-packages/requests_oauthlib/oauth2_session.py", line 203, in fetch_token
    self._client.parse_request_body_response(r.text, scope=self.scope)
  File "/var/www/bugs.jqueryui.com/private/pve/local/lib/python2.7/site-packages/oauthlib/oauth2/rfc6749/clients/base.py", line 409, in parse_request_body_response
    self.token = parse_token_response(body, scope=scope)
  File "/var/www/bugs.jqueryui.com/private/pve/local/lib/python2.7/site-packages/oauthlib/oauth2/rfc6749/parameters.py", line 376, in parse_token_response
    validate_token_parameters(params)
  File "/var/www/bugs.jqueryui.com/private/pve/local/lib/python2.7/site-packages/oauthlib/oauth2/rfc6749/parameters.py", line 386, in validate_token_parameters
    raise MissingTokenError(description="Missing access token parameter.")
MissingTokenError: (missing_token) Missing access token parameter.
```

**Comment by aaugustin** [comment]
This could happen because the redirect URL gets cut halfway somehow?

**Comment by rjollos** [comment]
I guess we could just trap the exception and display a friendly message using `add_warning` (`trac.web.chrome`). Should the message be?: __Invalid request. Please try to login again.__

**Comment by aaugustin** [comment]
Yes, let's do that.

**Comment by rjollos** [comment]
Finally managed to get a setup running locally that allows testing against the GitHub API, using [ngrok](https://developer.github.com/webhooks/configuring/). I'll writeup steps later on.

While I'm unsure how to force the issue to be reproduced, I did at least make sure that the exception is handled the way we want by inserting `raise oauthlib.oauth2.MissingTokenError("Failure!")` into the `try` statement.
